# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c23fa5a60d45f270757a3f3ba9f7a7460001ba02f0d44d3df861e43a0d6eaa456d9790d7d29d3c59ab91a43a6839ddb8c72b025227d38f65897905e78c92fecf

test:
  secret_key_base: 237c906a8172eee0a1088d31f6ad2278e6d081e3cf4d96674327d4cd68a310b5cb4d6902e2c600206929cb2ed30fa9593f5ef90e1925fa220b24898a2440832e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
